// Code generated by ogen, DO NOT EDIT.

package api

// Ref: #/components/schemas/ErrorResponseSchema
type ErrorResponseSchema struct {
	Message string `json:"message"`
}

// GetMessage returns the value of Message.
func (s *ErrorResponseSchema) GetMessage() string {
	return s.Message
}

// SetMessage sets the value of Message.
func (s *ErrorResponseSchema) SetMessage(val string) {
	s.Message = val
}

func (*ErrorResponseSchema) getHealthRes() {}

// GetHealthOK is response for GetHealth operation.
type GetHealthOK struct{}

func (*GetHealthOK) getHealthRes() {}
